version: '3'

includes:
  hadolint:
    taskfile: ./taskfiles/lint/hadolint.yml
  build:
    taskfile: ./taskfiles/build/build_push.yml
  deploy:
    taskfile: ./taskfiles/deploy/gitops.yml
  argocd:
    taskfile: ./taskfiles/deploy/argocd.yml
  trivy:
    taskfile: ./taskfiles/scan/trivy.yml
  k6:
    taskfile: ./taskfiles/qa/k6.yml
  owasp-zap:
    taskfile: ./taskfiles/dast/owasp-zap.yml