version: '3'

includes:
  hadolint:
    taskfile: ./taskfiles/lint/hadolint.yml
  build:
    taskfile: ./taskfiles/build/build_push.yml
  deploy:
    taskfile: ./taskfiles/deploy/gitops.yml
  argocd:
    taskfile: ./taskfiles/deploy/argocd.yml
  trivy:
    taskfile: ./taskfiles/scan/trivy.yml