name: CI/CD for all bracnhes, but ignore branch main
on:
  push:
    branches-ignore:
      - 'main'
      - 'refs/tags/**'
jobs:
  hadolint:
    name: handolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone taskfiles repository
        uses: actions/checkout@v4
        with:
          repository: rootsh/taskfiles
          path: taskfiles
          ref: v0.0.3
          ssh-key: ${{ secrets.PRIVATE_KEY_TASKFILES_DEPLOY }}
      - name: Lint Dockerfile
        run: |
          task hadolint:dockerfile
  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: read
        checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: -D errcheck
  unit_test:
    runs-on: ubuntu-latest
    needs: [golangci]
    container:
      image: golang:1.22
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Unit Test
        run: |
          cd src
          go test
          